# Reusable workflow for releases; to eject, you can replace this file with
# https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/release.yml
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ryansonshine/ryansonshine/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    env:
      DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
      TS_NODE_IGNORE: "false"
      TS_NODE_FILES: "true"
